### ISSUE TITLE
Project continuation

### ISSUE THREAD

**Issue by kwizzn** [jaredhanson/passport-remember-me#16]
I would like to get a discussion started about the future of this project. I believe it is still being used but the last commit dates back 3 years ago.

I think this plugin is well authored and there's not much to do besides upgrading the passport dependency to v0.3, which would fix some of the issues and PRs. 

@jaredhanson, I believe you simply do not have the time. Would you agree to assign contributors that volunteer to work on this project? I am short of time myself but maybe some of the other contributors are interested? What about you, @ilich, @pravin-d, @bazineta, @jackred, @vincentbriglia, @numasi, @shaharyakir, @eddyystop?

**Comment by numasi** [comment]
I'm a bit of a newbie in node and passport, but in the near future when I got used to the system more, I would be glad to help if I can!

**Comment by kvaillant** [comment]
Great Idea !

**Comment by ilich** [comment]
I like the idea. I can help with the project from time to time. I think the project is doing what is supposed to do. We just have to fix broken dependencies and upload the fix to npm.

**Comment by erebel55** [comment]
I would also appreciate an update.

**Comment by Laro88** [comment]
I have been trying to get the remember-me to work, however I might be struggling with stale / dead code. Is the remember-me alive and if not what are the alternatives?

**Comment by kwizzn** [comment]
From what I know, there's no real alternative, that's why I wanted to get this discussion started. The plugin works perfectly if the passport dependency is up to date. I guess most people fork this repo to fix just that.

I just mailed @jaredhanson with an invitation to join this discussion.

For my part, I could at least upgrade the dependency if Jared assigns me as a contributor both here and on npm.

**Comment by jaredhanson** [comment]
Feel free to fork this package, and release it under a new name (say `passport-remember-me2`), where the maintainer is clearly identified.

Unfortunately, my experience with trying to get maintainers is that their willingness to stay involved subsides quicky, and I'm back to square one.  If a fork is well maintained, I'll post a notice on the README here and a link to it.

**Comment by jaredhanson** [comment]
If this is simply a matter of updating the dependency, that is no longer necessary.  There's a fix in passport core that solves that issue, and as such there's no major (or minor) changes needed here, as far as I know.

The general design goal of separating out strategies was so that they could be "finished" and not require work.  Lack of commits for years at a time does not signal a dead project, but rather one that is done.
