### ISSUE TITLE
Cannot read property 'remember_me' of undefined

### ISSUE THREAD

**Issue by ghost** [jaredhanson/passport-remember-me#24]
I just test this strategy and it wont work. When i go to any route it show the error message:
Cannot read property 'remember_me' of undefined
I followed exactly as the Usage in README.md

**Comment by og2t** [comment]
+1

**Comment by Kudos5** [comment]
Hi. I had this problem too. Turns out I had forgotten to use cookie-parser.

**Comment by bryanprimus** [comment]
i had the same problem .. how to solve this?

**Comment by binhlk** [comment]
@bryantobing12 see @Kudos5 comment.

**Comment by bryanprimus** [comment]
Yeah i see. I forgot that cookie parser no longer bundled in express. Just Install cookie-parser and add cookieparser() to your middleware. Thank you

**Comment by saikat709** [comment]
Thank you guys, I had the same issue then your solution, installing cookie-parser, worked.
